# Estimate the wing beat frequency from blobs.
# The blob csv file is generated by trackblobs.
# The format of the file is a header row.  For example:
# ['blob 128 of track id 29', '619', '161', '409', '6', '4']
#    blob and track ID         frame   x      y   width height
# followed by the intensity values of the blob image (width x height).

import numpy as np
import matplotlib.pyplot as plt
import scipy.fftpack
import csv

# Load the blob csv file.
csvpath = '../data/Gull1-20120813_14-57-30_out/Gull1-20120813_14-57-30-blobs_0002.csv'
#getheader = True;

# Get the blob time series.
frame = []
x = []
y = []
w = []
h = []
with open(csvpath, 'rb') as csvfile:
    rdr = csv.reader(csvfile)
    for row in rdr:
        print row
        if getheader:
            # Look for header
            if row[0].count('blob') == 0:
                 continue
            else:
                 frame.append(int(row[1]))
                 x.append(int(row[2]))
                 y.append(int(row[3]))
                 w.append(int(row[4]))
                 h.append(int(row[5]))

# Fill in missing frames.


# plot the time series
plt.plot(x,y)
plt.title('TRACK')
plt.show()

plt.plot(frame,h)
plt.ylabel('height')
plt.xlabel('frame')
plt.show()

plt.plot(frame,w)
plt.ylabel('width')
plt.xlabel('frame')
plt.show()



# Fourier Transform
yf = scipy.fftpack.fft(h-np.mean(h))
N = len(h)
dt = 1.0/30.0;
frq = np.linspace(0.0, 1.0/(2.0*dt), N/2)


